{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "01fa966e-1720-4920-a7c3-48a29b8ee89e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Project 2 -- [Karim] [El-Sharkawy]\n",
    "\n",
    "# Question 1A\n",
    "\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "# Define url as the url page we want to parse\n",
    "url = 'https://books.toscrape.com/'\n",
    "response = requests.get(url)\n",
    "\n",
    "# response.content gives the content inside the <response> tag\n",
    "soup = BeautifulSoup(response.content,'html.parser')\n",
    "\n",
    "# .prettify() formats the code so it's easier to read\n",
    "print(soup.prettify())\n",
    "\n",
    "# Question 1B\n",
    "soup.title.text.strip()\n",
    "\n",
    "# Question 2\n",
    "for x in soup.select('.nav-list li a'):\n",
    "    print(x.text.strip())\n",
    "\n",
    "# Question 3A\n",
    "for x in soup.select('.nav-list li a'):\n",
    "    print('Category:', x.text.strip(), 'link:', x.get('href'))\n",
    "    \n",
    "# Question 3B\n",
    "for x in soup.select('.nav-list li a'):\n",
    "    if x.text.strip() == \"Romance\":\n",
    "        print('romance_url is', x.get('href')) #how to get the full link?\n",
    "        \n",
    "# Question 4A\n",
    "url = 'https://books.toscrape.com/catalogue/category/books/romance_8/index.html'\n",
    "response = requests.get(url)\n",
    "soup = BeautifulSoup(response.content,'html.parser')\n",
    "\n",
    "print(soup.prettify())\n",
    "\n",
    "# Question 4B\n",
    "for x in soup.select('.product_pod h3 a'):\n",
    "    print(x.text)\n",
    "\n",
    "# Question 5A\n",
    "url= \"http://books.toscrape.com/catalogue/category/books/romance_8/\"\n",
    "url=url.rsplit('/',1)[0]\n",
    "\n",
    "print(soup.find('li', class_='next'))\n",
    "next_link = soup.find('li', class_='next')\n",
    "\n",
    "if next_link:\n",
    "    next_link = next_link.find('a')\n",
    "    if next_link:\n",
    "        next_link = next_link.get('href').split(\"/\")[-1]\n",
    "        #Combining the two parts to make the new url (next page)\n",
    "        next_url = url+\"/\"+ next_link\n",
    "        print(f\"URL given: {next_url}\")\n",
    "\n",
    "# Question 5B\n",
    "for x in soup.select('a', class_=\"next\"):\n",
    "    print(x.text)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
