print("Hello! I'm Karim El-Sharkawy and I'm a Math student at Purdue. I work on a mix of theoretical and applied topics")
print("I can use python along with multiple packages, including sklearn. I've worked on a multitude of different projects in terms of theoretical and applied math, both of which relied on my knowledge of Python")
print("I'm eager to work and often do things without being told to. I am a great asset to your company because of my experience working with many different topics on multiple projects")
print("On top of math and coding, I like to work on environmental projects and learn languages. Currently, I'm trying to become fluent in German and hoping to bring recycling to my local Mosque")
print("Thank you for your time and have a great day!")